development:
  adapter: postgresql
  encoding: unicode
  database: fortune_responders_development
  pool: 5
  username: wbzyl
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: fortune_responders_test
  pool: 5
  username: wbzyl
  password:
